name: Dev Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - dev

jobs:
  dev_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Pytest
        uses: bfelch/boobjuice-web-app/.github/workflows/python-test.yml

      - name: Docker Image
        uses: ./.github/workflows/docker-image