name: Dev Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - dev

jobs:
  pytest:
    uses: ./.github/workflows/python-test.yml@dev

  docker_image:
    needs: pytest
    uses: ./.github/workflows/docker-image.yml@dev