name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  release:
    types:
      - published

jobs:
  pytest:
    uses: bfelch/boobjuice-web-app/.github/workflows/python-test.yml@main

  docker_image:
    needs: pytest
    uses: bfelch/boobjuice-web-app/.github/workflows/docker-image.yml@main
    secrets: inherit